/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PontoDeEntregaService } from "../pontoDeEntrega.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PontoDeEntregaCreateInput } from "./PontoDeEntregaCreateInput";
import { PontoDeEntregaWhereInput } from "./PontoDeEntregaWhereInput";
import { PontoDeEntregaWhereUniqueInput } from "./PontoDeEntregaWhereUniqueInput";
import { PontoDeEntregaFindManyArgs } from "./PontoDeEntregaFindManyArgs";
import { PontoDeEntregaUpdateInput } from "./PontoDeEntregaUpdateInput";
import { PontoDeEntrega } from "./PontoDeEntrega";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PontoDeEntregaControllerBase {
  constructor(
    protected readonly service: PontoDeEntregaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PontoDeEntrega })
  @nestAccessControl.UseRoles({
    resource: "PontoDeEntrega",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: PontoDeEntregaCreateInput
  ): Promise<PontoDeEntrega> {
    return await this.service.create({
      data: {
        ...data,

        viagemId: {
          connect: data.viagemId,
        },
      },
      select: {
        createdAt: true,
        id: true,
        idPontoEntrega: true,
        latitude: true,
        longitude: true,
        nomePonto: true,
        updatedAt: true,

        viagemId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PontoDeEntrega] })
  @ApiNestedQuery(PontoDeEntregaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PontoDeEntrega",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<PontoDeEntrega[]> {
    const args = plainToClass(PontoDeEntregaFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        idPontoEntrega: true,
        latitude: true,
        longitude: true,
        nomePonto: true,
        updatedAt: true,

        viagemId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PontoDeEntrega })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PontoDeEntrega",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: PontoDeEntregaWhereUniqueInput
  ): Promise<PontoDeEntrega | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        idPontoEntrega: true,
        latitude: true,
        longitude: true,
        nomePonto: true,
        updatedAt: true,

        viagemId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PontoDeEntrega })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PontoDeEntrega",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: PontoDeEntregaWhereUniqueInput,
    @common.Body() data: PontoDeEntregaUpdateInput
  ): Promise<PontoDeEntrega | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          viagemId: {
            connect: data.viagemId,
          },
        },
        select: {
          createdAt: true,
          id: true,
          idPontoEntrega: true,
          latitude: true,
          longitude: true,
          nomePonto: true,
          updatedAt: true,

          viagemId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PontoDeEntrega })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PontoDeEntrega",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: PontoDeEntregaWhereUniqueInput
  ): Promise<PontoDeEntrega | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          idPontoEntrega: true,
          latitude: true,
          longitude: true,
          nomePonto: true,
          updatedAt: true,

          viagemId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
