/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ViagemService } from "../viagem.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ViagemCreateInput } from "./ViagemCreateInput";
import { ViagemWhereInput } from "./ViagemWhereInput";
import { ViagemWhereUniqueInput } from "./ViagemWhereUniqueInput";
import { ViagemFindManyArgs } from "./ViagemFindManyArgs";
import { ViagemUpdateInput } from "./ViagemUpdateInput";
import { Viagem } from "./Viagem";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ViagemControllerBase {
  constructor(
    protected readonly service: ViagemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Viagem })
  @nestAccessControl.UseRoles({
    resource: "Viagem",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: ViagemCreateInput): Promise<Viagem> {
    return await this.service.create({
      data: {
        ...data,

        comprovantes: data.comprovantes
          ? {
              connect: data.comprovantes,
            }
          : undefined,

        pontoDeEntregas: data.pontoDeEntregas
          ? {
              connect: data.pontoDeEntregas,
            }
          : undefined,
      },
      select: {
        aprovadaEm: true,

        comprovantes: {
          select: {
            id: true,
          },
        },

        comprovantes_enviados: true,
        criadoEm: true,
        deletadoEm: true,
        envioConcluido: true,
        id: true,
        idExterno: true,
        manifestado: true,

        pontoDeEntregas: {
          select: {
            id: true,
          },
        },

        rejeitadaEm: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Viagem] })
  @ApiNestedQuery(ViagemFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Viagem",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Viagem[]> {
    const args = plainToClass(ViagemFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        aprovadaEm: true,

        comprovantes: {
          select: {
            id: true,
          },
        },

        comprovantes_enviados: true,
        criadoEm: true,
        deletadoEm: true,
        envioConcluido: true,
        id: true,
        idExterno: true,
        manifestado: true,

        pontoDeEntregas: {
          select: {
            id: true,
          },
        },

        rejeitadaEm: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Viagem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Viagem",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ViagemWhereUniqueInput
  ): Promise<Viagem | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        aprovadaEm: true,

        comprovantes: {
          select: {
            id: true,
          },
        },

        comprovantes_enviados: true,
        criadoEm: true,
        deletadoEm: true,
        envioConcluido: true,
        id: true,
        idExterno: true,
        manifestado: true,

        pontoDeEntregas: {
          select: {
            id: true,
          },
        },

        rejeitadaEm: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Viagem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Viagem",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ViagemWhereUniqueInput,
    @common.Body() data: ViagemUpdateInput
  ): Promise<Viagem | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          comprovantes: data.comprovantes
            ? {
                connect: data.comprovantes,
              }
            : undefined,

          pontoDeEntregas: data.pontoDeEntregas
            ? {
                connect: data.pontoDeEntregas,
              }
            : undefined,
        },
        select: {
          aprovadaEm: true,

          comprovantes: {
            select: {
              id: true,
            },
          },

          comprovantes_enviados: true,
          criadoEm: true,
          deletadoEm: true,
          envioConcluido: true,
          id: true,
          idExterno: true,
          manifestado: true,

          pontoDeEntregas: {
            select: {
              id: true,
            },
          },

          rejeitadaEm: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Viagem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Viagem",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ViagemWhereUniqueInput
  ): Promise<Viagem | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          aprovadaEm: true,

          comprovantes: {
            select: {
              id: true,
            },
          },

          comprovantes_enviados: true,
          criadoEm: true,
          deletadoEm: true,
          envioConcluido: true,
          id: true,
          idExterno: true,
          manifestado: true,

          pontoDeEntregas: {
            select: {
              id: true,
            },
          },

          rejeitadaEm: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
