/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  ValidateNested,
  IsEnum,
  IsBoolean,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { ComprovanteWhereUniqueInput } from "../../comprovante/base/ComprovanteWhereUniqueInput";
import { EnumViagemComprovantesEnviados } from "./EnumViagemComprovantesEnviados";
import { PontoDeEntregaWhereUniqueInput } from "../../pontoDeEntrega/base/PontoDeEntregaWhereUniqueInput";

@InputType()
class ViagemUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  aprovadaEm?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ComprovanteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ComprovanteWhereUniqueInput)
  @IsOptional()
  @Field(() => ComprovanteWhereUniqueInput, {
    nullable: true,
  })
  comprovantes?: ComprovanteWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumViagemComprovantesEnviados,
  })
  @IsEnum(EnumViagemComprovantesEnviados)
  @IsOptional()
  @Field(() => EnumViagemComprovantesEnviados, {
    nullable: true,
  })
  comprovantes_enviados?: "PENDENTE" | "ENVIO_PARCIAL" | "ENVIADOS";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  criadoEm?: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletadoEm?: Date | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  envioConcluido?: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  idExterno?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  manifestado?: boolean;

  @ApiProperty({
    required: false,
    type: () => PontoDeEntregaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PontoDeEntregaWhereUniqueInput)
  @IsOptional()
  @Field(() => PontoDeEntregaWhereUniqueInput, {
    nullable: true,
  })
  pontoDeEntregas?: PontoDeEntregaWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  rejeitadaEm?: Date | null;
}

export { ViagemUpdateInput as ViagemUpdateInput };
