/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ComprovanteService } from "../comprovante.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ComprovanteCreateInput } from "./ComprovanteCreateInput";
import { ComprovanteWhereInput } from "./ComprovanteWhereInput";
import { ComprovanteWhereUniqueInput } from "./ComprovanteWhereUniqueInput";
import { ComprovanteFindManyArgs } from "./ComprovanteFindManyArgs";
import { ComprovanteUpdateInput } from "./ComprovanteUpdateInput";
import { Comprovante } from "./Comprovante";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ComprovanteControllerBase {
  constructor(
    protected readonly service: ComprovanteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Comprovante })
  @nestAccessControl.UseRoles({
    resource: "Comprovante",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: ComprovanteCreateInput
  ): Promise<Comprovante> {
    return await this.service.create({
      data: {
        ...data,

        viagemId: {
          connect: data.viagemId,
        },
      },
      select: {
        analisadoEm: true,
        aprovadoEm: true,
        createdAt: true,
        deletadoEm: true,
        id: true,
        idExterno: true,
        rejeitadoEm: true,
        resultadoAnalise: true,
        tipoComprovante: true,
        updatedAt: true,
        urlComprovante: true,

        viagemId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Comprovante] })
  @ApiNestedQuery(ComprovanteFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Comprovante",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Comprovante[]> {
    const args = plainToClass(ComprovanteFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        analisadoEm: true,
        aprovadoEm: true,
        createdAt: true,
        deletadoEm: true,
        id: true,
        idExterno: true,
        rejeitadoEm: true,
        resultadoAnalise: true,
        tipoComprovante: true,
        updatedAt: true,
        urlComprovante: true,

        viagemId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Comprovante })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Comprovante",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ComprovanteWhereUniqueInput
  ): Promise<Comprovante | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        analisadoEm: true,
        aprovadoEm: true,
        createdAt: true,
        deletadoEm: true,
        id: true,
        idExterno: true,
        rejeitadoEm: true,
        resultadoAnalise: true,
        tipoComprovante: true,
        updatedAt: true,
        urlComprovante: true,

        viagemId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Comprovante })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Comprovante",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ComprovanteWhereUniqueInput,
    @common.Body() data: ComprovanteUpdateInput
  ): Promise<Comprovante | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          viagemId: {
            connect: data.viagemId,
          },
        },
        select: {
          analisadoEm: true,
          aprovadoEm: true,
          createdAt: true,
          deletadoEm: true,
          id: true,
          idExterno: true,
          rejeitadoEm: true,
          resultadoAnalise: true,
          tipoComprovante: true,
          updatedAt: true,
          urlComprovante: true,

          viagemId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Comprovante })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Comprovante",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ComprovanteWhereUniqueInput
  ): Promise<Comprovante | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          analisadoEm: true,
          aprovadoEm: true,
          createdAt: true,
          deletadoEm: true,
          id: true,
          idExterno: true,
          rejeitadoEm: true,
          resultadoAnalise: true,
          tipoComprovante: true,
          updatedAt: true,
          urlComprovante: true,

          viagemId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
